name: Show Attendance (Log View)

on:
  workflow_dispatch:
    inputs:
      lecture_date:
        description: "Enter Lecture Date (DDMMYYYY) Example: 27022026"
        required: true
        type: string

permissions:
  actions: read
  contents: read

jobs:
  show-attendance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI & jq
        run: |
          sudo apt update
          sudo apt install gh jq -y

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      # Convert DDMMYYYY → YYYY-MM-DD
      - name: Convert Date Format
        run: |
          INPUT="${{ github.event.inputs.lecture_date }}"

          if [[ ! "$INPUT" =~ ^[0-9]{8}$ ]]; then
            echo "Invalid format. Use DDMMYYYY"
            exit 1
          fi

          DAY=${INPUT:0:2}
          MONTH=${INPUT:2:2}
          YEAR=${INPUT:4:4}

          FORMATTED_DATE="$YEAR-$MONTH-$DAY"
          echo "FORMATTED_DATE=$FORMATTED_DATE" >> $GITHUB_ENV
          echo "Converted Date: $FORMATTED_DATE"

      - name: Fetch Successful Attendance Runs
        run: |
          gh run list \
            --repo ${{ github.repository }} \
            --workflow="Classroom Attendance" \
            --status=success \
            --json databaseId,createdAt \
            --limit 200 > runs.json

      - name: Download and Display Attendance
        run: |
          echo "======================================"
          echo "Attendance for $FORMATTED_DATE"
          echo "======================================"

          count=0

          for row in $(jq -c '.[]' runs.json); do
            run_id=$(echo "$row" | jq -r '.databaseId')
            created=$(echo "$row" | jq -r '.createdAt' | cut -d'T' -f1)

            if [ "$created" == "$FORMATTED_DATE" ]; then
              
              mkdir -p run_$run_id

              gh run download $run_id \
                --repo ${{ github.repository }} \
                -D run_$run_id >/dev/null 2>&1 || continue

              file=$(find run_$run_id -name "attendance.txt" | head -n 1)

              if [ -f "$file" ]; then
                name=$(grep "Name:" "$file" | cut -d':' -f2- | xargs)
                user=$(grep "GitHub Username:" "$file" | cut -d':' -f2- | xargs)
                topic=$(grep "Lecture Topic:" "$file" | cut -d':' -f2- | xargs)

                echo "$((++count)). $name | $user | $topic"
              fi
            fi
          done

          echo "--------------------------------------"
          echo "Total Students Present: $count"
          echo "======================================"
